### ISSUE TITLE
Socket for MySQL

### ISSUE THREAD

**Issue by olofbokedal** [oddhill/oddenvironment#10]
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/opt/boxen/data/mysql/socket' (2)

Can we fix MySQL so that it connects through a proper socket? Perhaps overhaul the entire ini-file?

**Comment by jenslind** [comment]
> /opt/boxen/data/mysql/socket

Make sure to make a complete uninstall of boxen :)
