### ISSUE TITLE
MySQL server not possible to manage via services

### ISSUE THREAD

**Issue by olofbokedal** [oddhill/oddenvironment#11]
services mysql start/stop/restart doesn't have any effect :(

restart/start prints "Success!" no matter what, and stop always prints "Something went wrong". Perhaps the service is configured to keep running at all times, making it impossible to stop?

**Comment by jenslind** [comment]
Sounds like you are running mysql as root.
Try run

```
brew services stop mysql56
```

If mysql is started as root it will complain.

**Comment by olofbokedal** [comment]
That worked, and then I tried `brew services stop mysql` again. Which now worked... I'm able to start/stop/restart mysql through oddenv now. Perhaps I hadn't rebooted in a while so mysql might have been ran as root prior rebooting.

Anyhow, not able to reproduce this anymore.
