### ISSUE TITLE
Set the public folder as the default document root

### ISSUE THREAD

**Issue by NormySan** [oddhill/oddenvironment#12]
I think we should assume that all sites has their document root in a public folder.

I propose we modify the httpd-vhost.conf to reflect this. The code below is from my local computer still runnin on boxen (I assume the public folder is still not used as default in oddenv?).

```
<VirtualHost *:80>
  UseCanonicalName off
  VirtualDocumentRoot /Users/christoffer/Sites/%1/public
</VirtualHost>

<VirtualHost *:443>
  UseCanonicalName off
  VirtualDocumentRoot /Users/christoffer/Sites/%1/public
  SSLEngine on
  SSLCertificateFile /opt/boxen/data/ssl/dev.crt
  SSLCertificateKeyFile /opt/boxen/data/ssl/dev.key
</VirtualHost>
```

For people still running sites not updated the only thing they have to do is move the site into a public folder.

This changes removes the need of a .htaccess file to redirect to the public folder on sites running an old version of odddrupal and removes the ugly public folder in the url.

**Comment by jenslind** [comment]
Sounds good to me 👍
