### ISSUE TITLE
Warnings when using drush

### ISSUE THREAD

**Issue by ErikJohansson93** [oddhill/oddenvironment#16]
I get the following warning when I use Drush:

PHP Warning:  Version warning: Imagick was compiled against Image Magick version 1683 but version 1684 is loaded. Imagick will run but may behave surprisingly in Unknown on line 0

Pls fix.

**Comment by jenslind** [comment]
```
brew update && brew upgrade
```

Might fix it.

**Comment by ErikJohansson93** [comment]
brew update && brew upgrade fixed the issue.
