### ISSUE TITLE
Disable xdebug for PHP CLI

### ISSUE THREAD

**Issue by NormySan** [oddhill/oddenvironment#17]
I took a quick look at the code but could not find any obvious way to change this. Xdebug should be disabled because of performance issues when running PHP in CLI mode (command line).

When using composer for example this message is shown:

> You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug

**Comment by jenslind** [comment]
After looking at some issues on homebrew regarding this exact issues I think we have to do the following:

Move the content of this file: `/usr/local/etc/php/5.5/conf.d/ext-xdebug.ini` into our `php.ini` and then remove the file. Then create a `php-cli.ini` which does not include the content from `ext-xdebug.ini`.

**Comment by jenslind** [comment]
Should be fixed now, can you run `oddenv` and confirm?

**Comment by NormySan** [comment]
@jenslind Seems to be working great! 👍
