### ISSUE TITLE
.dev is now a gTLD and won't work in Chrome

### ISSUE THREAD

**Issue by AdamGerthel** [oddhill/oddenvironment#23]
See https://ma.ttias.be/chrome-force-dev-domains-https-via-preloaded-hsts/ for reference.

**TL;DR**
.dev domains for local development wont work since the latest chrome release. The only workaround is to change TLD.

**Solution**
Update `manifests/dnsmasq.pp` with another TLD on line 3 and 15.

**Comment by AdamGerthel** [comment]
Update: For some reason `.local` doesn't work for me, but `.foobar` does which is why I haven't made a pull request for this issue.

**Comment by olofbokedal** [comment]
As stated in https://tools.ietf.org/html/rfc2606, there are four TLDs reserved for testing and documentation:

- .test
- .example
- .invalid
- .localhost

.test isn't that good since it might cause confusion with the test server, but .localhost should do it.

So I propose a change to .localhost

**Comment by AdamGerthel** [comment]
Agree, localhost seems like the best option

**Comment by AdamGerthel** [comment]
Committed https://github.com/oddhill/oddenvironment/commit/5448d70dde15b63aa56658abc20c1e59bef5ffe3
