### ISSUE TITLE
Default xdebug settings

### ISSUE THREAD

**Issue by AdamGerthel** [oddhill/oddenvironment#24]
Having xdebug enabled in PHP causes massive decreases in site speed performance. Is it really necessary to have enabled as default?

**Comment by olofbokedal** [comment]
Nah, could be activated when needed.

**Comment by AdamGerthel** [comment]
Committed https://github.com/oddhill/oddenvironment/commit/58267fdf865d35506eaba495ac68e7d4d8686831
