### ISSUE TITLE
MySQL server has gone away

### ISSUE THREAD

**Issue by olofbokedal** [oddhill/oddenvironment#5]
I'm getting "MySQL server has gone away" error from time to time when working on Drupal sites.

Perhaps the configuration needs some tweaking?

**Comment by jenslind** [comment]
What is the output of:

``` shell
mysqld --print-defaults 
```

**Comment by olofbokedal** [comment]
`--user=mysql --default-storage-engine=InnoDB --socket=/tmp/mysql.sock --key-buffer-size=32M --myisam-recover=FORCE,BACKUP --max-allowed-packet=512M --max-connect-errors=1000000 --datadir=/usr/local/var/mysql --expire-logs-days=14 --sync-binlog=1 --tmp-table-size=32M --max-heap-table-size=32M --query-cache-type=0 --query-cache-size=0 --max-connections=500 --thread-cache-size=50 --table-definition-cache=4096 --innodb-flush-method=O_DIRECT --innodb-log-files-in-group=2 --innodb-log-file-size=128M --innodb-flush-log-at-trx-commit=1 --innodb-file-per-table=1 --innodb-buffer-pool-size=2G`
