### ISSUE TITLE
Yeoman can't find globally installed generators

### ISSUE THREAD

**Issue by olofbokedal** [oddhill/oddenvironment#8]
I installed the keystone generator using `npm install -g generator-keystone`, but Yeoman can't find it when I try to run `yo keystone`. It works if I install the generator locally.

Haven't tried with any other generators yet.

**Comment by jenslind** [comment]
Can you run a `oddenv` and restart your shell and see if the issue has been resolved?

**Comment by olofbokedal** [comment]
Works! :tongue:

**Comment by Andyliwr** [comment]
How to make it works.

**Comment by olofbokedal** [comment]
The `oddenv` command updated my environment to the latest version, which in turn solved my problem.

How are you experiencing the problem @Andyliwr? An easy thing to try is to force the update, `oddenv --force`.
